#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias mysql='/usr/local/mysql/bin/mysql --password=mymysql1 -u root'
alias la='ls -a'
alias visc='/Users/cheddar/viscpt'
#alias mpirun='/opt/local/lib/openmpi/bin/mpirun'
#alias mpicc='/opt/local/lib/openmpi/bin/mpicc'
alias lc='wc -l'
alias cls='clear'
alias ll="ls -lhSp | awk '{print \$5\"  \t\"substr(\$0, index(\$0,\$9))}' | tail -n +2"
